# Generated by Django 6.0.3 on 2026-03-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('time_from_building_1', models.IntegerField(default=100, verbose_name='Время от корпуса №1 (мин)')),
                ('time_from_building_3', models.IntegerField(default=100, verbose_name='Время от корпуса №3 (мин)')),
                ('time_from_building_5', models.IntegerField(default=100, verbose_name='Время от корпуса №5 (мин)')),
                ('nearest_building', models.CharField(blank=True, help_text='Например: №1, №3, №5', max_length=10, verbose_name='Ближайший корпус')),
                ('cuisine_type', models.CharField(blank=True, max_length=100, verbose_name='Тип кухни')),
                ('avg_price', models.IntegerField(blank=True, null=True, verbose_name='Средний чек (₽)')),
                ('opening_hours', models.CharField(blank=True, max_length=200, verbose_name='Часы работы')),
                ('photo_url', models.URLField(blank=True, verbose_name='Ссылка на фото')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('rating', models.FloatField(default=0, verbose_name='Рейтинг')),
                ('rating_count', models.IntegerField(default=0, verbose_name='Количество оценок')),
            ],
            options={
                'verbose_name': 'Заведение',
                'verbose_name_plural': 'Заведения',
            },
        ),
    ]
