# Generated by Django 6.0.4 on 2026-04-17 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='nearest_building',
            field=models.CharField(blank=True, help_text='Например: №1, №3 или №5', max_length=5, verbose_name='Ближайший корпус'),
        ),
    ]
