# Generated by Django 6.0.4 on 2026-04-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_place_nearest_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='cuisine_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Вид заведения'),
        ),
    ]
