from django.db import migrations

def create_places(apps, schema_editor):
    Place = apps.get_model('places', 'Place')
    
    places_list = [
        {
            'name': 'All week',
            'address': 'ул. Кирова, 86',
            'time_from_building_1': 7,
            'time_from_building_3': 8,
            'time_from_building_5': 14,
            'nearest_building': '1',
            'cuisine_type': 'столовая',
            'avg_price': 300,
            'opening_hours': '08:00-17:00',
            'photo_url': '',
            'latitude': 55.014185,
            'longitude': 82.949439,
        },
        {
            'name': 'All week',
            'address': 'ул. Кирова, 29',
            'time_from_building_1': 10,
            'time_from_building_3': 7,
            'time_from_building_5': 10,
            'nearest_building': '3',
            'cuisine_type': 'столовая',
            'avg_price': 300,
            'opening_hours': '08:00-17:00',
            'photo_url': '',
            'latitude': 55.016654,
            'longitude': 82.948022,
        },
        {
            'name': 'Barbq',
            'address': 'ул. Кирова, 29',
            'time_from_building_1': 14,
            'time_from_building_3': 8,
            'time_from_building_5': 10,
            'nearest_building': '3',
            'cuisine_type': 'фастфуд',
            'avg_price': 1000,
            'opening_hours': '11:00-23:00',
            'photo_url': '',
            'latitude': 55.016573,
            'longitude': 82.947936,
        },
        {
            'name': 'BeanGo',
            'address': 'ул. Кирова, 29',
            'time_from_building_1': 14,
            'time_from_building_3': 8,
            'time_from_building_5': 10,
            'nearest_building': '3',
            'cuisine_type': 'кафе',
            'avg_price': 300,
            'opening_hours': '07:00-20:00',
            'photo_url': '',
            'latitude': 55.016680,
            'longitude': 82.948073,
        },
        {
            'name': 'Bierhof',
            'address': 'ул. Восход, 24',
            'time_from_building_1': 12,
            'time_from_building_3': 7,
            'time_from_building_5': 12,
            'nearest_building': '3',
            'cuisine_type': 'бар',
            'avg_price': 1500,
            'opening_hours': '12:00-00:00',
            'photo_url': '',
            'latitude': 55.012926,
            'longitude': 82.942477,
        },
        {
            'name': 'Brandchef',
            'address': 'ул. Восход, 46',
            'time_from_building_1': 15,
            'time_from_building_3': 11,
            'time_from_building_5': 8,
            'nearest_building': '5',
            'cuisine_type': 'ресторан',
            'avg_price': 700,
            'opening_hours': '11:00-23:00',
            'photo_url': '',
            'latitude': 55.019464,
            'longitude': 82.951077,
        },
        {
            'name': 'Bubble bar',
            'address': 'ул. Кирова, 108',
            'time_from_building_1': 3,
            'time_from_building_3': 5,
            'time_from_building_5': 13,
            'nearest_building': '1',
            'cuisine_type': 'кафе',
            'avg_price': 300,
            'opening_hours': '10:00-19:00',
            'photo_url': '',
            'latitude': 55.012515,
            'longitude': 82.953355,
        },
        {
            'name': 'Coffee club',
            'address': 'ул. Кирова, 82',
            'time_from_building_1': 6,
            'time_from_building_3': 2,
            'time_from_building_5': 5,
            'nearest_building': '3',
            'cuisine_type': 'кафе',
            'avg_price': 350,
            'opening_hours': '08:30-21:30',
            'photo_url': '',
            'latitude': 55.014660,
            'longitude': 82.948021,
        },
        {
            'name': 'Doner king',
            'address': 'ул. Кирова, 108, к. 6',
            'time_from_building_1': 3,
            'time_from_building_3': 5,
            'time_from_building_5': 14,
            'nearest_building': '1',
            'cuisine_type': 'фастфуд',
            'avg_price': 450,
            'opening_hours': '08:00-23:00',
            'photo_url': '',
            'latitude': 55.013234,
            'longitude': 82.952041,
        },
        {
            'name': 'Dose Of Coffee',
            'address': 'ул. Кирова, 108',
            'time_from_building_1': 3,
            'time_from_building_3': 5,
            'time_from_building_5': 14,
            'nearest_building': '1',
            'cuisine_type': 'кафе',
            'avg_price': 300,
            'opening_hours': '08:00-19:00',
            'photo_url': '',
            'latitude': 55.012515,
            'longitude': 82.953355,
        },
        {
            'name': 'Enthusiasm Coffee Roasters',
            'address': 'ул. Кирова, 27В',
            'time_from_building_1': 13,
            'time_from_building_3': 11,
            'time_from_building_5': 9,
            'nearest_building': '5',
            'cuisine_type': 'кафе',
            'avg_price': 300,
            'opening_hours': '08:00-22:00',
            'photo_url': '',
            'latitude': 55.017318,
            'longitude': 82.945914,
        },
        {
            'name': 'Fit cafe',
            'address': 'ул. Кирова, 82',
            'time_from_building_1': 7,
            'time_from_building_3': 2,
            'time_from_building_5': 4,
            'nearest_building': '3',
            'cuisine_type': 'кафе',
            'avg_price': 300,
            'opening_hours': '09:00-21:00',
            'photo_url': '',
            'latitude': 55.014779,
            'longitude': 82.948209,
        },
        {
            'name': 'Habibi food',
            'address': 'ул. Кирова, 27',
            'time_from_building_1': 15,
            'time_from_building_3': 10,
            'time_from_building_5': 11,
            'nearest_building': '3',
            'cuisine_type': 'фастфуд',
            'avg_price': 400,
            'opening_hours': 'Круглосуточно',
            'photo_url': '',
            'latitude': 55.016914,
            'longitude': 82.944619,
        },
        {
            'name': 'Kartel Rolls',
            'address': 'ул. Гурьевская, 89',
            'time_from_building_1': 10,
            'time_from_building_3': 10,
            'time_from_building_5': 7,
            'nearest_building': '5',
            'cuisine_type': 'кафе',
            'avg_price': 600,
            'opening_hours': '11:00-22:30',
            'photo_url': '',
            'latitude': 55.016355,
            'longitude': 82.955122,
        },
        {
            'name': 'Mgrill',
            'address': 'ул. Кирова, 27',
            'time_from_building_1': 13,
            'time_from_building_3': 11,
            'time_from_building_5': 9,
            'nearest_building': '5',
            'cuisine_type': 'фастфуд',
            'avg_price': 300,
            'opening_hours': 'Круглосуточно',
            'photo_url': '',
            'latitude': 55.017223,
            'longitude': 82.945784,
        },
        {
            'name': 'Pho Luu',
            'address': 'ул. Чехова, 140',
            'time_from_building_1': 10,
            'time_from_building_3': 10,
            'time_from_building_5': 7,
            'nearest_building': '5',
            'cuisine_type': 'ресторан',
            'avg_price': 300,
            'opening_hours': '10:00-20:00',
            'photo_url': '',
            'latitude': 55.016498,
            'longitude': 82.955267,
        },
        {
            'name': 'Quince',
            'address': 'ул. Сакко и Ванцетти, 25/1',
            'time_from_building_1': 18,
            'time_from_building_3': 13,
            'time_from_building_5': 18,
            'nearest_building': '3',
            'cuisine_type': 'ресторан',
            'avg_price': 1000,
            'opening_hours': '09:00-22:00',
            'photo_url': '',
            'latitude': 55.013977,
            'longitude': 82.936149,
        },
        {
            'name': 'Sinlun',
            'address': 'ул. Кирова, 29',
            'time_from_building_1': 14,
            'time_from_building_3': 9,
            'time_from_building_5': 10,
            'nearest_building': '3',
            'cuisine_type': 'китайское кафе',
            'avg_price': 2000,
            'opening_hours': '11:00-00:00',
            'photo_url': '',
            'latitude': 55.016339,
            'longitude': 82.948560,
        },
        {
            'name': 'Безумно',
            'address': 'ул. Гурьевская, 55',
            'time_from_building_1': 7,
            'time_from_building_3': 7,
            'time_from_building_5': 8,
            'nearest_building': '5',
            'cuisine_type': 'фастфуд',
            'avg_price': 300,
            'opening_hours': '10:00-23:00',
            'photo_url': '',
            'latitude': 55.014509,
            'longitude': 82.952730,
        },
        {
            'name': 'Бодрый день',
            'address': 'ул. Кирова, 113/2',
            'time_from_building_1': 10,
            'time_from_building_3': 11,
            'time_from_building_5': 12,
            'nearest_building': '1',
            'cuisine_type': 'кафе',
            'avg_price': 400,
            'opening_hours': '08:00-20:00',
            'photo_url': '',
            'latitude': 55.013519,
            'longitude': 82.955030,
        },
        {
            'name': 'Бузовар',
            'address': 'ул. Московская улица, 97',
            'time_from_building_1': 11,
            'time_from_building_3': 9,
            'time_from_building_5': 11,
            'nearest_building': '3',
            'cuisine_type': 'ресторан',
            'avg_price': 350,
            'opening_hours': '09:00-21:00',
            'photo_url': '',
            'latitude': 55.018205,
            'longitude': 82.943625,
        },
        {
            'name': 'Быстрое питание',
            'address': 'ул. Тургенева, 159',
            'time_from_building_1': 13,
            'time_from_building_3': 14,
            'time_from_building_5': 10,
            'nearest_building': '5',
            'cuisine_type': 'столовая',
            'avg_price': 350,
            'opening_hours': '08:00-20:00',
            'photo_url': '',
            'latitude': 55.016878,
            'longitude': 82.959013,
        },
        {
            'name': 'Ваша пекарня',
            'address': 'ул. Гурьевская, 55',
            'time_from_building_1': 7,
            'time_from_building_3': 8,
            'time_from_building_5': 9,
            'nearest_building': '1',
            'cuisine_type': 'пекарня',
            'avg_price': 150,
            'opening_hours': '09:00-20:00',
            'photo_url': '',
            'latitude': 55.014953,
            'longitude': 82.953304,
        },
        {
            'name': 'Вебстрим',
            'address': 'ул. Гурьевская, 51',
            'time_from_building_1': 1,
            'time_from_building_3': 5,
            'time_from_building_5': 11,
            'nearest_building': '1',
            'cuisine_type': 'столовая',
            'avg_price': 250,
            'opening_hours': '09:00-16:30',
            'photo_url': '',
            'latitude': 55.013563,
            'longitude': 82.951147,
        },
        {
            'name': 'Вилка Ложка',
            'address': 'ул. Кирова, 108',
            'time_from_building_1': 3,
            'time_from_building_3': 5,
            'time_from_building_5': 14,
            'nearest_building': '1',
            'cuisine_type': 'столовая',
            'avg_price': 350,
            'opening_hours': '08:00-22:00',
            'photo_url': '',
            'latitude': 55.012383,
            'longitude': 82.953477,
        },
        {
            'name': 'Горыныч',
            'address': 'ул. Кирова, 50',
            'time_from_building_1': 13,
            'time_from_building_3': 11,
            'time_from_building_5': 13,
            'nearest_building': '3',
            'cuisine_type': 'ресторан',
            'avg_price': 2500,
            'opening_hours': '09:00-00:00',
            'photo_url': '',
            'latitude': 55.017610,
            'longitude': 82.941117,
        },
        {
            'name': 'Гриль хаус',
            'address': 'ул. Гурьевская, 53',
            'time_from_building_1': 6,
            'time_from_building_3': 6,
            'time_from_building_5': 7,
            'nearest_building': '5',
            'cuisine_type': 'фастфуд',
            'avg_price': 600,
            'opening_hours': '11:00-23:00',
            'photo_url': '',
            'latitude': 55.013892,
            'longitude': 82.952030,
        },
        {
            'name': 'Грильница',
            'address': 'ул. Бориса Богаткова, 64',
            'time_from_building_1': 10,
            'time_from_building_3': 6,
            'time_from_building_5': 2,
            'nearest_building': '5',
            'cuisine_type': 'фастфуд',
            'avg_price': 450,
            'opening_hours': '09:00-23:00',
            'photo_url': '',
            'latitude': 55.016560,
            'longitude': 82.951266,
        },
        {
            'name': 'Додо Пицца',
            'address': 'ул. Кирова, 46/1',
            'time_from_building_1': 13,
            'time_from_building_3': 11,
            'time_from_building_5': 13,
            'nearest_building': '3',
            'cuisine_type': 'ресторан',
            'avg_price': 500,
            'opening_hours': '10:00-23:00',
            'photo_url': '',
            'latitude': 55.018268,
            'longitude': 82.939654,
        },
        {
            'name': 'Дракоша',
            'address': 'ул. Гурьевская, 53',
            'time_from_building_1': 6,
            'time_from_building_3': 6,
            'time_from_building_5': 8,
            'nearest_building': '5',
            'cuisine_type': 'ресторан',
            'avg_price': 600,
            'opening_hours': '10:00-22:00',
            'photo_url': '',
            'latitude': None,
            'longitude': None,
        },
        {
            'name': 'Друзья',
            'address': 'ул. Гурьевская, 51',
            'time_from_building_1': 4,
            'time_from_building_3': 5,
            'time_from_building_5': 10,
            'nearest_building': '1',
            'cuisine_type': 'кафе',
            'avg_price': 200,
            'opening_hours': '08:00-16:30',
            'photo_url': '',
            'latitude': None,
            'longitude': None,
        },
        {
            'name': 'Заверните',
            'address': 'ул. Тургенева, 182, к. 1',
            'time_from_building_1': 12,
            'time_from_building_3': 12,
            'time_from_building_5': 9,
            'nearest_building': '5',
            'cuisine_type': 'фастфуд',
            'avg_price': 350,
            'opening_hours': '11:00-20:00',
            'photo_url': '',
            'latitude': 55.017116,
            'longitude': 82.956764,
        },
        {
            'name': 'Закусочная',
            'address': 'ул. Ленинградская, 75',
            'time_from_building_1': 5,
            'time_from_building_3': 6,
            'time_from_building_5': 3,
            'nearest_building': '5',
            'cuisine_type': 'фастфуд',
            'avg_price': 250,
            'opening_hours': '07:00-19:00',
            'photo_url': '',
            'latitude': 55.015926,
            'longitude': 82.952643,
        },
        {
            'name': 'Имбирь',
            'address': 'ул. Гурьевская, 76А',
            'time_from_building_1': 9,
            'time_from_building_3': 10,
            'time_from_building_5': 6,
            'nearest_building': '5',
            'cuisine_type': 'ресторан',
            'avg_price': 600,
            'opening_hours': '11:00-23:00',
            'photo_url': '',
            'latitude': 55.015551,
            'longitude': 82.955047,
        },
        {
            'name': 'Кабанчик',
            'address': 'ул. Восход, 32',
            'time_from_building_1': 12,
            'time_from_building_3': 6,
            'time_from_building_5': 8,
            'nearest_building': '3',
            'cuisine_type': 'ресторан',
            'avg_price': 1200,
            'opening_hours': '12:00-23:00',
            'photo_url': '',
            'latitude': 55.015325,
            'longitude': 82.945499,
        },
        {
            'name': 'Кафе',
            'address': 'ул. Кирова, 116',
            'time_from_building_1': 12,
            'time_from_building_3': 12,
            'time_from_building_5': 14,
            'nearest_building': '1',
            'cuisine_type': 'кафе',
            'avg_price': 250,
            'opening_hours': '08:00-22:00',
            'photo_url': '',
            'latitude': 55.010983,
            'longitude': 82.957478,
        },
        {
            'name': 'Киоск фастфудной продукции',
            'address': 'ул. Гурьевская, 55',
            'time_from_building_1': 8,
            'time_from_building_3': 8,
            'time_from_building_5': 4,
            'nearest_building': '5',
            'cuisine_type': 'фастфуд',
            'avg_price': None,
            'opening_hours': 'Круглосуточно',
            'photo_url': '',
            'latitude': 55.015044,
            'longitude': 82.953351,
        },
        {
            'name': 'Космо Хот-Дог',
            'address': 'ул. Кирова, 108, к.1',
            'time_from_building_1': 3,
            'time_from_building_3': 5,
            'time_from_building_5': 13,
            'nearest_building': '1',
            'cuisine_type': 'фастфуд',
            'avg_price': 150,
            'opening_hours': '08:00-20:00',
            'photo_url': '',
            'latitude': 55.013006,
            'longitude': 82.952724,
        },
        {
            'name': 'Кофе - дело тонкое',
            'address': 'ул. Кирова, 113/2',
            'time_from_building_1': 10,
            'time_from_building_3': 11,
            'time_from_building_5': 12,
            'nearest_building': '1',
            'cuisine_type': 'кафе',
            'avg_price': 250,
            'opening_hours': '08:00-20:00',
            'photo_url': '',
            'latitude': 55.013589,
            'longitude': 82.955043,
        },
        {
            'name': 'Кочевник',
            'address': 'ул. Толстого, 121',
            'time_from_building_1': 11,
            'time_from_building_3': 7,
            'time_from_building_5': 4,
            'nearest_building': '5',
            'cuisine_type': 'ресторан',
            'avg_price': 1500,
            'opening_hours': '11:00-00:00',
            'photo_url': '',
            'latitude': 55.016869,
            'longitude': 82.952892,
        },
        {
            'name': 'Лаваш и мясо',
            'address': 'ул. Кирова, 108, к.1',
            'time_from_building_1': 3,
            'time_from_building_3': 5,
            'time_from_building_5': 13,
            'nearest_building': '1',
            'cuisine_type': 'фастфуд',
            'avg_price': 350,
            'opening_hours': 'Круглосуточно',
            'photo_url': '',
            'latitude': 55.013103,
            'longitude': 82.952491,
        },
        {
            'name': 'Лагманная',
            'address': 'ул. Богаткова, 64, к. 1',
            'time_from_building_1': 10,
            'time_from_building_3': 6,
            'time_from_building_5': 3,
            'nearest_building': '5',
            'cuisine_type': 'кафе',
            'avg_price': 400,
            'opening_hours': '09:00-22:00',
            'photo_url': '',
            'latitude': 55.016818,
            'longitude': 82.951517,
        },
        {
            'name': 'Мастер хинкали',
            'address': 'ул. Сакко и Ванцетти, 108',
            'time_from_building_1': 22,
            'time_from_building_3': 20,
            'time_from_building_5': 17,
            'nearest_building': '5',
            'cuisine_type': 'фастфуд',
            'avg_price': 300,
            'opening_hours': '10:00-20:00',
            'photo_url': '',
            'latitude': 55.022948,
            'longitude': 82.952875,
        },
        {
            'name': 'Мачете',
            'address': 'ул. Гурьевская, 64/1',
            'time_from_building_1': 10,
            'time_from_building_3': 10,
            'time_from_building_5': 7,
            'nearest_building': '5',
            'cuisine_type': 'фастфуд',
            'avg_price': 300,
            'opening_hours': '10:00-04:00',
            'photo_url': '',
            'latitude': 55.013637,
            'longitude': 82.952423,
        },
        {
            'name': 'Мята Lounge',
            'address': 'ул. Кирова, 29/1',
            'time_from_building_1': 9,
            'time_from_building_3': 7,
            'time_from_building_5': 9,
            'nearest_building': '3',
            'cuisine_type': 'бар',
            'avg_price': 1500,
            'opening_hours': '12:00-02:00',
            'photo_url': '',
            'latitude': 55.016420,
            'longitude': 82.947619,
        },
        {
            'name': 'Наш лаваш',
            'address': 'ул. Кирова, 27',
            'time_from_building_1': 16,
            'time_from_building_3': 10,
            'time_from_building_5': 12,
            'nearest_building': '3',
            'cuisine_type': 'фастфуд',
            'avg_price': 250,
            'opening_hours': 'Круглосуточно',
            'photo_url': '',
            'latitude': 55.016876,
            'longitude': 82.944713,
        },
        {
            'name': 'Папа Джонс',
            'address': 'ул. Толстого, 115',
            'time_from_building_1': 11,
            'time_from_building_3': 7,
            'time_from_building_5': 3,
            'nearest_building': '5',
            'cuisine_type': 'кафе',
            'avg_price': 600,
            'opening_hours': '11:00-23:00',
            'photo_url': '',
            'latitude': 55.017061,
            'longitude': 82.952095,
        },
        {
            'name': 'Пельмешка',
            'address': 'ул. Гурьевская, 78',
            'time_from_building_1': 10,
            'time_from_building_3': 11,
            'time_from_building_5': 12,
            'nearest_building': '1',
            'cuisine_type': 'столовая',
            'avg_price': 300,
            'opening_hours': '10:00-19:00',
            'photo_url': '',
            'latitude': 55.013519,
            'longitude': 82.955030,
        },
        {
            'name': 'Пицца Синица',
            'address': 'ул. Кирова, 113A',
            'time_from_building_1': 7,
            'time_from_building_3': 7,
            'time_from_building_5': 8,
            'nearest_building': '5',
            'cuisine_type': 'ресторан',
            'avg_price': 600,
            'opening_hours': '09:30-23:00',
            'photo_url': '',
            'latitude': 55.013180,
            'longitude': 82.953387,
        },
        {
            'name': 'Пончики',
            'address': 'ул. Кирова, 113B',
            'time_from_building_1': 6,
            'time_from_building_3': 7,
            'time_from_building_5': 8,
            'nearest_building': '5',
            'cuisine_type': 'кафе',
            'avg_price': 200,
            'opening_hours': '09:00-21:30',
            'photo_url': '',
            'latitude': 55.013375,
            'longitude': 82.952803,
        },
        {
            'name': 'Русские блины',
            'address': 'ул. Кирова, 27',
            'time_from_building_1': 15,
            'time_from_building_3': 10,
            'time_from_building_5': 11,
            'nearest_building': '3',
            'cuisine_type': 'фастфуд',
            'avg_price': 400,
            'opening_hours': 'Круглосуточно',
            'photo_url': '',
            'latitude': 55.016974,
            'longitude': 82.944492,
        },
        {
            'name': 'Сайори',
            'address': 'ул. Восход, 46',
            'time_from_building_1': 12,
            'time_from_building_3': 9,
            'time_from_building_5': 7,
            'nearest_building': '5',
            'cuisine_type': 'ресторан',
            'avg_price': 600,
            'opening_hours': '11:00-22:00',
            'photo_url': '',
            'latitude': 55.019067,
            'longitude': 82.950082,
        },
        {
            'name': 'Связь',
            'address': 'ул. Кирова, 86',
            'time_from_building_1': 5,
            'time_from_building_3': 1,
            'time_from_building_5': 6,
            'nearest_building': '3',
            'cuisine_type': 'столовая',
            'avg_price': 300,
            'opening_hours': '09:00-16:00',
            'photo_url': '',
            'latitude': 55.013904,
            'longitude': 82.948271,
        },
        {
            'name': 'Сирушо',
            'address': 'ул. Кирова, 82',
            'time_from_building_1': 6,
            'time_from_building_3': 2,
            'time_from_building_5': 5,
            'nearest_building': '3',
            'cuisine_type': 'кафе',
            'avg_price': 300,
            'opening_hours': '09:00-19:00',
            'photo_url': '',
            'latitude': 55.014545,
            'longitude': 82.948083,
        },
        {
            'name': 'Солнечный день',
            'address': 'ул. Ленинградская, 100',
            'time_from_building_1': 11,
            'time_from_building_3': 11,
            'time_from_building_5': 8,
            'nearest_building': '5',
            'cuisine_type': 'столовая',
            'avg_price': 300,
            'opening_hours': '08:00-21:00',
            'photo_url': '',
            'latitude': 55.013731,
            'longitude': 82.956352,
        },
        {
            'name': 'Старый Узген',
            'address': 'ул. Кирова, 116, к. 1',
            'time_from_building_1': 12,
            'time_from_building_3': 13,
            'time_from_building_5': 14,
            'nearest_building': '1',
            'cuisine_type': 'кафе',
            'avg_price': 250,
            'opening_hours': '07:00-22:00',
            'photo_url': '',
            'latitude': 55.011022,
            'longitude': 82.957407,
        },
        {
            'name': 'Суши Make',
            'address': 'ул. Гурьевская, 53',
            'time_from_building_1': 5,
            'time_from_building_3': 6,
            'time_from_building_5': 7,
            'nearest_building': '1',
            'cuisine_type': 'кафе',
            'avg_price': 500,
            'opening_hours': '11:00-22:00',
            'photo_url': '',
            'latitude': 55.013796,
            'longitude': 82.951903,
        },
        {
            'name': 'Тамагочи',
            'address': 'ул. Гурьевская, 89',
            'time_from_building_1': 10,
            'time_from_building_3': 10,
            'time_from_building_5': 7,
            'nearest_building': '5',
            'cuisine_type': 'столовая',
            'avg_price': 600,
            'opening_hours': '12:00-00:30',
            'photo_url': '',
            'latitude': None,
            'longitude': None,
        },
        {
            'name': 'Хан Буз',
            'address': 'ул. Гурьевская, 53',
            'time_from_building_1': 6,
            'time_from_building_3': 6,
            'time_from_building_5': 7,
            'nearest_building': '5',
            'cuisine_type': 'ресторан',
            'avg_price': 400,
            'opening_hours': '09:00-21:00',
            'photo_url': '',
            'latitude': 55.013992,
            'longitude': 82.952155,
        },
        {
            'name': 'Харакири',
            'address': 'ул. Бориса Богаткова, 63',
            'time_from_building_1': 12,
            'time_from_building_3': 8,
            'time_from_building_5': 5,
            'nearest_building': '5',
            'cuisine_type': 'ресторан',
            'avg_price': 700,
            'opening_hours': '10:00-03:00',
            'photo_url': '',
            'latitude': 55.018072,
            'longitude': 82.951969,
        },
        {
            'name': 'Чикен-гриль',
            'address': 'ул. Нижегородская, 17А',
            'time_from_building_1': 8,
            'time_from_building_3': 6,
            'time_from_building_5': 10,
            'nearest_building': '3',
            'cuisine_type': 'фастфуд',
            'avg_price': 400,
            'opening_hours': '10:00-22:00',
            'photo_url': '',
            'latitude': 55.015017,
            'longitude': 82.942839,
        },
        {
            'name': 'Чудо',
            'address': 'ул. Гурьевская, 53',
            'time_from_building_1': 6,
            'time_from_building_3': 6,
            'time_from_building_5': 8,
            'nearest_building': '5',
            'cuisine_type': 'фастфуд',
            'avg_price': 300,
            'opening_hours': 'Круглосуточно',
            'photo_url': '',
            'latitude': 55.014062,
            'longitude': 82.952116,
        },
        {
            'name': 'ЮжанеГорожане',
            'address': 'ул. Кирова, 23',
            'time_from_building_1': 14,
            'time_from_building_3': 12,
            'time_from_building_5': 14,
            'nearest_building': '3',
            'cuisine_type': 'ресторан',
            'avg_price': 1000,
            'opening_hours': 'проверить',
            'photo_url': '',
            'latitude': 55.019067,
            'longitude': 82.940156,
        },
    ]
    
    for place_data in places_list:
        # Проверяем, есть ли уже такое заведение
        obj, created = Place.objects.update_or_create(
            name=place_data['name'],
            address=place_data['address'],
            defaults=place_data
        )


def delete_places(apps, schema_editor):
    Place = apps.get_model('places', 'Place')
    Place.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('places', '0004_alter_place_cuisine_type'),
    ]

    operations = [
        migrations.RunPython(create_places, reverse_code=delete_places),
    ]