# Generated by Django 6.0.4 on 2026-05-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='student_discount',
            field=models.CharField(blank=True, max_length=20, verbose_name='Скидка для студентов'),
        ),
    ]
