# Generated by Django 6.0.4 on 2026-05-16 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_place_student_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='photo_url',
        ),
        migrations.RemoveField(
            model_name='review',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='place',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='place_photos/', verbose_name='Фото заведения'),
        ),
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='review_photos/', verbose_name='Фото'),
        ),
    ]
