# Generated by Django 6.0.4 on 2026-05-01 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_avatar_profile_bio_profile_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='animations',
            field=models.CharField(blank=True, default='on', max_length=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='font_size',
            field=models.CharField(blank=True, default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='greeting_style',
            field=models.CharField(blank=True, default='sweet', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='theme',
            field=models.CharField(blank=True, default='light', max_length=10),
        ),
    ]
