# Generated by Django 6.0.4 on 2026-05-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_animations_profile_font_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rating',
            field=models.FloatField(default=0, verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='profile',
            name='rating_count',
            field=models.IntegerField(default=0, verbose_name='Количество оценок'),
        ),
    ]
