# Generated by Django 6.0.4 on 2026-05-15 07:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_rating_profile_rating_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последняя активность'),
        ),
    ]
