from django.urls import path
from . import views

urlpatterns = [
    path('', views.roulette, name='roulette'),
    path('api/solo/save-params/', views.save_solo_params, name='save_solo_params'),
    path('api/solo/create/', views.create_solo_request, name='create_solo'),
    path('api/solo/find/', views.find_solo_match, name='find_solo'),
    path('api/solo/accept/', views.accept_solo_match, name='accept_solo'),
    path('api/group/save-params/', views.save_group_params, name='save_group_params'),
    path('api/group/create/', views.create_group_request, name='create_group'),
    path('api/group/find/', views.find_group_match, name='find_group'),
    path('api/group/create-company/', views.create_company, name='create_company'),
    path('api/group/join/<int:group_id>/', views.join_group, name='join_group'),
    path('messages/', views.messages_list, name='messages_list'),
    path('messages/<int:dialog_id>/', views.dialog_detail, name='dialog_detail'),
    path('api/messages/send/<int:dialog_id>/', views.send_message, name='send_message'),
    path('api/messages/unread/', views.get_unread_count, name='unread_count'),
    path('api/messages/new/<int:dialog_id>/', views.get_new_messages, name='new_messages'),
    path('api/dialog/delete/<int:dialog_id>/', views.delete_dialog, name='delete_dialog'),
    path('rate/<int:user_id>/', views.rate_user, name='rate_user'),
    path('api/solo/cancel/', views.cancel_solo_request, name='cancel_solo'),
    path('api/group/cancel/', views.cancel_group_request, name='cancel_group'),
    path('api/cancel-search/', views.cancel_search, name='cancel_search'),
    path('api/deactivate-search/', views.deactivate_search, name='deactivate_search'),
    path('api/clear-skipped/', views.clear_skipped, name='clear_skipped'),
    path('api/dialog/complete/<int:dialog_id>/', views.complete_meal, name='complete_meal'),
    path('api/dialog/check-status/<int:dialog_id>/', views.check_dialog_status, name='check_dialog_status'),
    path('group-rate/<int:dialog_id>/', views.group_rate, name='group_rate'),
    path('api/group-rate/save/<int:dialog_id>/', views.save_group_rating, name='save_group_rating'),
    path('api/group-rate/skip/<int:dialog_id>/', views.skip_group_rating, name='skip_group_rating'),
    path('api/group-rate/progress/<int:dialog_id>/', views.get_group_rating_progress, name='get_group_rating_progress'),
]