# Generated by Django 6.0.4 on 2026-05-02 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participants', models.ManyToManyField(related_name='dialogs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Диалог',
                'verbose_name_plural': 'Диалоги',
            },
        ),
        migrations.CreateModel(
            name='GroupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(choices=[('1', 'Корпус №1'), ('3', 'Корпус №3'), ('5', 'Корпус №5')], max_length=1, verbose_name='Корпус')),
                ('budget', models.CharField(choices=[('economy', 'До 200 ₽'), ('medium', '200–400 ₽'), ('high', 'От 400 ₽'), ('any', 'Не важно')], default='any', max_length=10, verbose_name='Бюджет')),
                ('needed_people', models.IntegerField(default=2, verbose_name='Сколько человек нужно')),
                ('current_members', models.IntegerField(default=1, verbose_name='Сколько уже собралось')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
                ('vk', models.CharField(blank=True, max_length=100, verbose_name='VK')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заявка (группа)',
                'verbose_name_plural': 'Заявки (группа)',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dialog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='roulette.dialog')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SoloRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(choices=[('1', 'Корпус №1'), ('3', 'Корпус №3'), ('5', 'Корпус №5')], max_length=1, verbose_name='Корпус')),
                ('budget', models.CharField(choices=[('economy', 'До 200 ₽'), ('medium', '200-400 ₽'), ('high', 'От 400 ₽'), ('any', 'Не важно')], default='any', max_length=10, verbose_name='Бюджет')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
                ('vk', models.CharField(blank=True, max_length=100, verbose_name='VK')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solo_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заявка (один)',
                'verbose_name_plural': 'Заявки (один)',
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='roulette.grouprequest')),
            ],
            options={
                'verbose_name': 'Участник группы',
                'verbose_name_plural': 'Участники группы',
                'unique_together': {('group', 'user')},
            },
        ),
    ]
