# Generated by Django 6.0.3 on 2026-04-28 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(choices=[('1', 'Корпус №1'), ('3', 'Корпус №3'), ('5', 'Корпус №5')], max_length=1, verbose_name='Корпус')),
                ('budget', models.CharField(choices=[('economy', 'До 200 ₽'), ('medium', '200–400 ₽'), ('high', 'От 400 ₽'), ('any', 'Не важно')], default='any', max_length=10, verbose_name='Бюджет')),
                ('needed_people', models.IntegerField(default=2, verbose_name='Сколько человек нужно')),
                ('current_members', models.IntegerField(default=1, verbose_name='Сколько уже собралось')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
                ('vk', models.CharField(blank=True, max_length=100, verbose_name='VK')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SoloRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(choices=[('1', 'Корпус №1'), ('3', 'Корпус №3'), ('5', 'Корпус №5')], max_length=1, verbose_name='Корпус')),
                ('budget', models.CharField(choices=[('economy', 'До 200 ₽'), ('medium', '200-400 ₽'), ('high', 'От 400 ₽'), ('any', 'Не важно')], default='any', max_length=10, verbose_name='Бюджет')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
                ('vk', models.CharField(blank=True, max_length=100, verbose_name='VK')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solo_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='roulette.grouprequest')),
            ],
            options={
                'unique_together': {('group', 'user')},
            },
        ),
    ]
