# Generated by Django 6.0.4 on 2026-04-28 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmember',
            options={'verbose_name': 'Участник группы', 'verbose_name_plural': 'Участники группы'},
        ),
        migrations.AlterModelOptions(
            name='grouprequest',
            options={'verbose_name': 'Заявка (группа)', 'verbose_name_plural': 'Заявки (группа)'},
        ),
        migrations.AlterModelOptions(
            name='solorequest',
            options={'verbose_name': 'Заявка (один)', 'verbose_name_plural': 'Заявки (один)'},
        ),
    ]
