# Generated by Django 6.0.4 on 2026-05-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0002_grouprequest_dialog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouprequest',
            name='needed_people',
            field=models.IntegerField(default=2, verbose_name='Сколько всего человек (включая тебя)'),
        ),
    ]
