# Generated by Django 6.0.4 on 2026-05-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0003_alter_grouprequest_needed_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouprequest',
            name='needed_people',
            field=models.IntegerField(default=3, verbose_name='Сколько всего человек (включая тебя)'),
        ),
    ]
