# Generated by Django 6.0.4 on 2026-05-13 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0004_alter_grouprequest_needed_people'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Оценка (1-5)')),
                ('text', models.TextField(blank=True, verbose_name='Комментарий')),
                ('photo_url', models.URLField(blank=True, verbose_name='Ссылка на фото')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to=settings.AUTH_USER_MODEL, verbose_name='Кто оценил')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to=settings.AUTH_USER_MODEL, verbose_name='Кого оценили')),
            ],
            options={
                'verbose_name': 'Оценка пользователя',
                'verbose_name_plural': 'Оценки пользователей',
                'unique_together': {('from_user', 'to_user', 'created_at')},
            },
        ),
    ]
