# Generated by Django 6.0.4 on 2026-05-14 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0005_userrating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dialog',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dialog',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_dialogs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dialog',
            name='is_meal_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='GroupRatingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_index', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dialog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_progress', to='roulette.dialog')),
                ('rated_users', models.ManyToManyField(blank=True, related_name='rated_by_in_group', to=settings.AUTH_USER_MODEL)),
                ('skipped_users', models.ManyToManyField(blank=True, related_name='skipped_by_in_group', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_ratings_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Прогресс оценки группы',
                'verbose_name_plural': 'Прогресс оценки групп',
                'unique_together': {('dialog', 'user')},
            },
        ),
        migrations.CreateModel(
            name='GroupUserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Оценка (1-5)')),
                ('text', models.TextField(blank=True, verbose_name='Комментарий')),
                ('photo_url', models.URLField(blank=True, verbose_name='Ссылка на фото')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dialog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_ratings', to='roulette.dialog')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_ratings_given', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_ratings_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Оценка в группе',
                'verbose_name_plural': 'Оценки в группах',
                'unique_together': {('dialog', 'from_user', 'to_user')},
            },
        ),
    ]
