# Generated by Django 6.0.4 on 2026-05-15 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0006_dialog_completed_at_dialog_completed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialog',
            name='is_group_chat',
            field=models.BooleanField(default=False),
        ),
    ]
